name: simple_dart_showcase_multilang
description: showcase using multilang
version: 0.0.1
publish_to: none

platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  simple_dart_blue_theme: ^0.0.1
  simple_dart_dark_theme: ^0.0.1
  simple_dart_default_theme: ^0.0.1
  simple_dart_modal_controller: ^0.0.1
  simple_dart_multilang_button: ^0.0.1
  simple_dart_multilang_checkbox: ^0.0.1
  simple_dart_multilang_file_picker: ^0.0.1
  simple_dart_multilang_form_panel: ^0.0.1
  simple_dart_multilang_headed_dialog: ^0.0.1
  simple_dart_multilang_headed_panel: ^0.0.1
  simple_dart_multilang_image_button: ^0.0.1
  simple_dart_multilang_object_table: ^0.0.1
  simple_dart_multilang_radio_field: ^0.0.1
  simple_dart_multilang_repository_table: ^0.0.1
  simple_dart_multilang_select_field: ^0.0.1
  simple_dart_multilang_table: ^0.0.1
  simple_dart_multilang_tabs_panel: ^0.0.1
  simple_dart_repository_table: ^0.0.1
  simple_dart_starter_multilang: ^0.0.1
  simple_dart_tabs_panel: ^0.0.1
  simple_dart_text_area_field: ^0.0.1
  simple_dart_text_field: ^0.0.1

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
